const roles = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  HEAD_CALL_CENTER: 'HEAD_CALL_CENTER',
  CALL_CENTER: 'CALL_CENTER',
  MARKETING: 'MARKETING',
  PLASTIC_CALL_CENTER: 'PLASTIC_CALL_CENTER',
  FRONT_OFFICE: 'FRONT_OFFICE',
  CREDIT_ADMIN: 'CREDIT_ADMIN',
  MANAGER_REPORT: 'MANAGER_REPORT',
  MANAGER_ASSIGNMENT: 'MANAGER_ASSIGNMENT'
};

export default roles;
